### ISSUE TITLE
Merge back to upstream?

### ISSUE THREAD

**Issue by languitar** [albfan/nerdtree-git-plugin#13]
Would it be possible to merge back the changes in this branch to the upstream version by Xuyuanp? The situation to find the right version of this plugin is actually quite confusing right now with two projects with diverging features and no hint in the readme how they differ.

**Comment by albfan** [comment]
If I recall correctly merge to upstream needs merge changes from up-upstream NERDTree as API has changed.

I'm interested anyway in merge to upstream.

Are you skilled to start this work? I can help you if you can start it. If not, I will try to start it as soon as possible.

See my first soft try was https://github.com/Xuyuanp/nerdtree-git-plugin/issues/35, but I get no progress on it

**Comment by languitar** [comment]
Unfortunately, I do not have much experience with VimL.

**Comment by albfan** [comment]
Ok. Let me see what can be done

**Comment by albfan** [comment]
It is done, I will open a PR, let's see what happen

**Comment by albfan** [comment]
https://github.com/Xuyuanp/nerdtree-git-plugin/pull/72
