### ISSUE TITLE
Hide square brackets around indicator symbols?

### ISSUE THREAD

**Issue by eivindml** [albfan/nerdtree-git-plugin#15]
Hi, is there any way to hide the square brackets around the indicator symbols? 

I think it would look cleaner without them. 

<img width="1310" alt="screen shot 2018-03-11 at 23 54 51" src="https://user-images.githubusercontent.com/202450/37259534-cfaea464-2587-11e8-90cf-c358de301a3a.png">

**Comment by albfan** [comment]
This is just a plugin for nedtree. Brackets comes from nedtree plugin itself

https://github.com/scrooloose/nerdtree/blob/509122df20e200b50e887c32cb7d92b19171a4ab/lib/nerdtree/flag_set.vim#L55

You need to ask there

NOTE: I rewrite this feature in https://github.com/albfan/easytree.vim, so if you want to try it, you can ask there to fix that
https://github.com/albfan/easytree.vim/blob/master/autoload/easytree.vim#L948
(I'm not sure how that will look like, but seems reasonable)
