### ISSUE TITLE
Multiple error in NixOs

### ISSUE THREAD

**Issue by mudrii** [albfan/nerdtree-git-plugin#18]
I am running NixOs and with fish and getting the error below when using the plugin.

```sh
Error detected while processing function 204[2]..205[14]..188[20]..191[8]..
155[25]..153[15]..265[5]..NERDTreeGitStatusRefreshListener[5]..NERDTreeGetG
itStatusPrefix:
line    6:
E716: Key not present in Dictionary: Slash()
E15: Invalid expression: b:NERDTree.root.path.str() . a:path.Slash()
Error detected while processing function 204[2]..205[14]..188[20]..191[8]..
155:
line   25:
E171: Missing :endif
Error detected while processing function 204[2]..205:
line   14:
E171: Missing :endif
``` 

Setting `set shell=sh`  in .vim.rc didn't help
Running from bash got the same error.

Any other solution I could try that can solve the error

**Comment by albfan** [comment]
Looking at nerdtree looks like now it is `nerdtree#slash()` so this plugin gets out of sync with latest versions of nerdtree.

PR welcome, no plans to upgrade this myself

**Comment by mudrii** [comment]
I fixed the issue after updating both to the unstable version in NixOs unstable

**Comment by albfan** [comment]
Nice!
